//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMUN_4 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMUN_4.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Dais uses Dais Consle to change information displayed in Main Page.In order to properly set your monitor, please follow the following procedures:
        ///
        ///1. Enter conference name, committee name and topic in Main Page.
        ///
        ///2. Use a cable to connect the computer to a second monitor, or projector. Make sure the second monitor (or projector) can be detected in the display settings of the computer.
        ///
        ///3. Press &quot;Windows&quot;(A flag on the bottom corner of your keyboard) and &quot;P&quot; keys together, and then select &quot;Extend&quot; Mode [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string h0P1Eng {
            get {
                return ResourceManager.GetString("h0P1Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主席团使用主席团控制台窗口来控制主页上显示的信息。为了正确设置您的显示器，请按照以下步骤设置：
        ///
        ///1. 在主页中输入会议名称、委员会名称和议题。
        ///
        ///2. 用数据线连接第二屏幕或投影仪。确保第二屏幕可以在电脑的显示设置中被检测到。
        ///
        ///3. 按下“Windows”（键盘下方角落的旗帜）和“P”键，在菜单中选择“扩展”（通常是第三个，仅在第二屏幕被检测到时有效）。这会使得第二屏幕变成第一屏幕右侧的扩展。
        ///
        ///4. 最后，拖动主页至屏幕右侧边缘，你会看见它从第二屏幕左侧边缘出现。 在第二屏幕中最大化主页。 的本地化字符串。
        /// </summary>
        public static string h0P1SimChn {
            get {
                return ResourceManager.GetString("h0P1SimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second Monitor 的本地化字符串。
        /// </summary>
        public static string h0P1TEng {
            get {
                return ResourceManager.GetString("h0P1TEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二屏幕 的本地化字符串。
        /// </summary>
        public static string h0P1TSimChn {
            get {
                return ResourceManager.GetString("h0P1TSimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommended screen resolution for Dais Console (i.e. Monitor of Dais) is 1920 * 1080, or 1366 * 768.Lowest Resolution for Main Page (i.e. Monitor for delegates) is 1024 * 768.The software is capable of adjusting to different resolutions. If a display problem occurs, please turn to the displaying settings of your computer to modify the scale percentage. (150%, 125%, 100%, etc.) 的本地化字符串。
        /// </summary>
        public static string h0P2Eng {
            get {
                return ResourceManager.GetString("h0P2Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主席团控制台（主席团屏幕）的推荐分辨率为 1920 * 1080，或 1366 * 768。主页（代表屏幕）的最低分辨率为 1024 * 768。本软件可自行适应不同分辨率，但若出现显示问题，请尝试在电脑的显示设置中调整缩放百分比（如150%，125% 或 100%）。 的本地化字符串。
        /// </summary>
        public static string h0P2SimChn {
            get {
                return ResourceManager.GetString("h0P2SimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Resolution 的本地化字符串。
        /// </summary>
        public static string h0P2TEng {
            get {
                return ResourceManager.GetString("h0P2TEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 屏幕分辨率 的本地化字符串。
        /// </summary>
        public static string h0P2TSimChn {
            get {
                return ResourceManager.GetString("h0P2TSimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you do not have access to a second monitor, an alternative solution is to display Dais Console to the delegates. 的本地化字符串。
        /// </summary>
        public static string h0P3Eng {
            get {
                return ResourceManager.GetString("h0P3Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若您无法使用第二屏幕，一个替代的方案是向代表展示主席团控制台。 的本地化字符串。
        /// </summary>
        public static string h0P3SimChn {
            get {
                return ResourceManager.GetString("h0P3SimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solo Monitor 的本地化字符串。
        /// </summary>
        public static string h0P3TEng {
            get {
                return ResourceManager.GetString("h0P3TEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单独显示器 的本地化字符串。
        /// </summary>
        public static string h0P3TSimChn {
            get {
                return ResourceManager.GetString("h0P3TSimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor Settings 的本地化字符串。
        /// </summary>
        public static string h0TEng {
            get {
                return ResourceManager.GetString("h0TEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示器设置 的本地化字符串。
        /// </summary>
        public static string h0TSimChn {
            get {
                return ResourceManager.GetString("h0TSimChn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Data and File&quot; in the left column to access File Management. You can create, modify or delete a record of a file submitted, including file name, location, sponsors and signatories. 的本地化字符串。
        /// </summary>
        public static string h10p1eng {
            get {
                return ResourceManager.GetString("h10p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击左栏中的“文件与数据”以访问文件管理。您可以创建、更改或删除被提交文件的记录，包括文件名、文件位置、起草国和附议国。 的本地化字符串。
        /// </summary>
        public static string h10p1schn {
            get {
                return ResourceManager.GetString("h10p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management System 的本地化字符串。
        /// </summary>
        public static string h10p1teng {
            get {
                return ResourceManager.GetString("h10p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件管理系统 的本地化字符串。
        /// </summary>
        public static string h10p1tschn {
            get {
                return ResourceManager.GetString("h10p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management 的本地化字符串。
        /// </summary>
        public static string h10teng {
            get {
                return ResourceManager.GetString("h10teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件管理 的本地化字符串。
        /// </summary>
        public static string h10tschn {
            get {
                return ResourceManager.GetString("h10tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After setting the time, click on Run or Pause to start or pause the timer. Click on Reset to set the timer back to its original value. Click on Clear to clear the timer. 的本地化字符串。
        /// </summary>
        public static string h11p1eng {
            get {
                return ResourceManager.GetString("h11p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置时间后，单击运行或暂停以开始或暂停计时器。单击重置以使计时器回到初始值。单击清除以使计时器归零。 的本地化字符串。
        /// </summary>
        public static string h11p1schn {
            get {
                return ResourceManager.GetString("h11p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer 的本地化字符串。
        /// </summary>
        public static string h11p1teng {
            get {
                return ResourceManager.GetString("h11p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器 的本地化字符串。
        /// </summary>
        public static string h11p1tschn {
            get {
                return ResourceManager.GetString("h11p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminder is used to keep a memo of a suspended event, or important notices. Click on clear to wipe it out. 的本地化字符串。
        /// </summary>
        public static string h11p2eng {
            get {
                return ResourceManager.GetString("h11p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备忘录可用于记录挂起的事件或重要通知。单击清除以清空。 的本地化字符串。
        /// </summary>
        public static string h11p2schn {
            get {
                return ResourceManager.GetString("h11p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminder 的本地化字符串。
        /// </summary>
        public static string h11p2teng {
            get {
                return ResourceManager.GetString("h11p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备忘录 的本地化字符串。
        /// </summary>
        public static string h11p2tschn {
            get {
                return ResourceManager.GetString("h11p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer and Reminder 的本地化字符串。
        /// </summary>
        public static string h11teng {
            get {
                return ResourceManager.GetString("h11teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器与备忘录 的本地化字符串。
        /// </summary>
        public static string h11tschn {
            get {
                return ResourceManager.GetString("h11tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language is selected when launching the software. Both English and Simplified Chinese are supported. To switch the language, save the conference progress and restart the software.
        ///
        ///Please notice that when saving into, or reading from Text Files under English language environment, Chinese characters may be displayed as digital gibberish. It is necessary to choose the corresponding language environment. 的本地化字符串。
        /// </summary>
        public static string h1p1eng {
            get {
                return ResourceManager.GetString("h1p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言可在程序启动时选择。本程序支持英文与简体中文。如需切换语言，保存会议进度后重新启动软件。
        ///
        ///请留意，在英文环境下读取或写入文本文档时，中文字符可能会成为乱码。请选取对应的语言环境。 的本地化字符串。
        /// </summary>
        public static string h1p1schn {
            get {
                return ResourceManager.GetString("h1p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Language 的本地化字符串。
        /// </summary>
        public static string h1p1teng {
            get {
                return ResourceManager.GetString("h1p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        public static string h1p1tschn {
            get {
                return ResourceManager.GetString("h1p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages 的本地化字符串。
        /// </summary>
        public static string h1teng {
            get {
                return ResourceManager.GetString("h1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string h1tsimchn {
            get {
                return ResourceManager.GetString("h1tsimchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please create &quot;Country.txt&quot; under the software path, and enter all countries in alphabetical order line by line. Do not leave any blank rows. 的本地化字符串。
        /// </summary>
        public static string h2p1eng {
            get {
                return ResourceManager.GetString("h2p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在软件根目录下创建“Country.txt”并逐行输入国家名。请务必不要留下空行。 的本地化字符串。
        /// </summary>
        public static string h2p1simchn {
            get {
                return ResourceManager.GetString("h2p1simchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Country List 的本地化字符串。
        /// </summary>
        public static string h2p1teng {
            get {
                return ResourceManager.GetString("h2p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家列表 的本地化字符串。
        /// </summary>
        public static string h2p1tsimchn {
            get {
                return ResourceManager.GetString("h2p1tsimchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you have preserved conference progress, it will be reloaded into the software next time when launching it. The software uses Country.txt,  File.txt, Event.txt and Data.txt under its startup path to save the records. To ensure the file management and data system functioning correctly, DO NOT modify or delete these text files. To start a new record, simply move these text files elsewhere, or start the program in another path. 的本地化字符串。
        /// </summary>
        public static string h2p2eng {
            get {
                return ResourceManager.GetString("h2p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若您在使用软件时保存了会议进度，它将会在下次启动软件时被重新加载。软件使用其根目录下的 Country.txt, File.txt，Event.txt 和 Data.txt 保存这些记录。为了使您能够正常使用文件管理和数据系统，请勿修改或删除这些文本文档。如需开始新的记录，请移除这些文本文档，或在其他目录下启动程序。 的本地化字符串。
        /// </summary>
        public static string h2p2simchn {
            get {
                return ResourceManager.GetString("h2p2simchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Data 的本地化字符串。
        /// </summary>
        public static string h2p2teng {
            get {
                return ResourceManager.GetString("h2p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载数据 的本地化字符串。
        /// </summary>
        public static string h2p2tsimchn {
            get {
                return ResourceManager.GetString("h2p2tsimchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Countries and Data 的本地化字符串。
        /// </summary>
        public static string h2teng {
            get {
                return ResourceManager.GetString("h2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载国家与数据 的本地化字符串。
        /// </summary>
        public static string h2tsimchn {
            get {
                return ResourceManager.GetString("h2tsimchn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To raise a motion, click on &quot;Motion&quot; in the left column. Make sure no other event is underway. (e.g. ticking speaker&apos;s list, roll call, voting, or another motion) Enter all information required to form a motion, and then you are given the option to display the motion in detail to the delegates by clicking on the &quot;Display to Screen&quot; button at the bottom. 的本地化字符串。
        /// </summary>
        public static string h3p1eng {
            get {
                return ResourceManager.GetString("h3p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击左栏中的“动议”以提起动议。确保无其他事项正在进行，如计时中的主发言名单、点名、表决或其他动议。输入所有构成动议的必要信息。您可以单击底部的“展示到屏幕”按钮以将动议细节展示给代表。 的本地化字符串。
        /// </summary>
        public static string h3p1schn {
            get {
                return ResourceManager.GetString("h3p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter all Information 的本地化字符串。
        /// </summary>
        public static string h3p1teng {
            get {
                return ResourceManager.GetString("h3p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入所有信息 的本地化字符串。
        /// </summary>
        public static string h3p1tschn {
            get {
                return ResourceManager.GetString("h3p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Pass&quot; to pass a motion, and then you will be directed to different pages depending on the motion type. Motions that are &quot;passed&quot; or &quot;failed&quot; will all be kept in conference record. 的本地化字符串。
        /// </summary>
        public static string h3p2eng {
            get {
                return ResourceManager.GetString("h3p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击“通过”以通过动议，然后您将被引导至处理相应动议的页面。“通过”或“未通过”的动议均会被会议记录保存。 的本地化字符串。
        /// </summary>
        public static string h3p2schn {
            get {
                return ResourceManager.GetString("h3p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prepare to Implement 的本地化字符串。
        /// </summary>
        public static string h3p2teng {
            get {
                return ResourceManager.GetString("h3p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备进行动议 的本地化字符串。
        /// </summary>
        public static string h3p2tschn {
            get {
                return ResourceManager.GetString("h3p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raise a Motion 的本地化字符串。
        /// </summary>
        public static string h3teng {
            get {
                return ResourceManager.GetString("h3teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提起动议 的本地化字符串。
        /// </summary>
        public static string h3tschn {
            get {
                return ResourceManager.GetString("h3tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The speaking time and total time of a moderated caucus was determined when a relative motion was passed. Then the page of inviting speakers will appear. Choose from the list on the left and click on &quot;Add&quot;. However, a much more efficient alterative is to search the first letter of the speaker invited, then use Up and Down keys to select, and press Enter key to add. To remove a speaker, select it in the list of speakers and click on &quot;Remove&quot;. When you are satisfied with the list, use buttons on the top-left c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string h4p1eng {
            get {
                return ResourceManager.GetString("h4p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有主持核心措施的发言时长和总时长在提起相关动议时即被决定。随后邀请发言人的页面将会出现。在左侧的列表中选择发言人并单击“添加”。然而，一个更有效率的方案是在搜索栏中输入国家名，并使用上下键选择，最终按下回车以添加。如需移除发言人，在发言人名单中选择，然后单击“移除”。当名单完成后，使用左上角的按钮（开始、暂停、下一位和结束）以主持磋商。 的本地化字符串。
        /// </summary>
        public static string h4p1schn {
            get {
                return ResourceManager.GetString("h4p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparations 的本地化字符串。
        /// </summary>
        public static string h4p1teng {
            get {
                return ResourceManager.GetString("h4p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备工作 的本地化字符串。
        /// </summary>
        public static string h4p1tschn {
            get {
                return ResourceManager.GetString("h4p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Start&quot; to begin or resume countdown. Click on &quot;Pause&quot; to pause countdown. Click on &quot;Next&quot; to move on to the next speaker on the list. Click on &quot;Expire&quot; to expire the motion at once.
        ///
        ///Multi-task is supported in the progress. For example, you are able to check speaker&apos;s list, or attendance status in relative pages while the moderated caucus is underway. Buttons on the top-left corner will still be functioning. When you want to return to the speaker-inviting page, click on &quot;Back&quot; to return to homep [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string h4p2eng {
            get {
                return ResourceManager.GetString("h4p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击“开始”以开始或继续计时。单击“暂停”以暂停计时。单击“下一位”以邀请下一位发言人。单击“结束”以立即结束当前动议。
        ///
        ///在这个过程中，您可以继续处理其他会议事务，如在相关页面中查看主发言名单或浏览出席状况。左上角的按钮仍然可以正常工作。如需返回邀请发言人的页面，单击“返回”以回到主页，然后在选择正在进行的有主持核心磋商。已发言或正在发言的代表不能从名单中被移除。 的本地化字符串。
        /// </summary>
        public static string h4p2schn {
            get {
                return ResourceManager.GetString("h4p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In Progress 的本地化字符串。
        /// </summary>
        public static string h4p2teng {
            get {
                return ResourceManager.GetString("h4p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行中 的本地化字符串。
        /// </summary>
        public static string h4p2tschn {
            get {
                return ResourceManager.GetString("h4p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the list of speakers is over, the program will give the number of more delegates allowed to speak, based on the total time left and the speaking time. You may invite more speakers, or expire the motion at once. If the list is over again, the motion is automatically expired. Delegates spoken in the motion will be recorded. 的本地化字符串。
        /// </summary>
        public static string h4p3eng {
            get {
                return ResourceManager.GetString("h4p3eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当发言人名单结束后，程序会给出剩余总时长和发言时长所允许的发言人数。您可以邀请更多的代表发言，或立即结束动议。当名单第二次结束时，动议自动结束。在此动议中发言的代表将会被记录。 的本地化字符串。
        /// </summary>
        public static string h4p3schn {
            get {
                return ResourceManager.GetString("h4p3schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expiration 的本地化字符串。
        /// </summary>
        public static string h4p3teng {
            get {
                return ResourceManager.GetString("h4p3teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束 的本地化字符串。
        /// </summary>
        public static string h4p3tschn {
            get {
                return ResourceManager.GetString("h4p3tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moderated Caucus 的本地化字符串。
        /// </summary>
        public static string h4teng {
            get {
                return ResourceManager.GetString("h4teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有主持核心磋商 的本地化字符串。
        /// </summary>
        public static string h4tschn {
            get {
                return ResourceManager.GetString("h4tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only total time is given in unmoderated caucus or free debate. Click on &quot;Start&quot; to begin or resume timing. Click on &quot;Pause&quot; to pause timing. Click on &quot;Expire&quot; to expire the motion at once.
        ///
        ///Multi-task is supported in the progress, but no new event should start until the motion is expired. 的本地化字符串。
        /// </summary>
        public static string h5p1eng {
            get {
                return ResourceManager.GetString("h5p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有总时长会在自由磋商和自由辩论中被显示。单击“开始”以开始或继续计时。单击“暂停”以暂停计时。单击“结束”以立即结束当前动议。
        ///
        ///在这个过程中，您可以继续处理其他会议事务，但不能开始新事项，直到当前动议结束。 的本地化字符串。
        /// </summary>
        public static string h5p1schn {
            get {
                return ResourceManager.GetString("h5p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do this Motion 的本地化字符串。
        /// </summary>
        public static string h5p1teng {
            get {
                return ResourceManager.GetString("h5p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行此动议 的本地化字符串。
        /// </summary>
        public static string h5p1tschn {
            get {
                return ResourceManager.GetString("h5p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unmoderated Caucus and Free Debate 的本地化字符串。
        /// </summary>
        public static string h5teng {
            get {
                return ResourceManager.GetString("h5teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由磋商和自由辩论 的本地化字符串。
        /// </summary>
        public static string h5tschn {
            get {
                return ResourceManager.GetString("h5tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To set up speaker&apos;s list, Click on &quot;Speaker&apos;s List&quot; on the left column, or in the dashboard. Choose from the list on the left and click on &quot;Add&quot;. However, a much more efficient alterative is to search the first letter of the speaker, then use Up and Down keys to select, and press Enter key to add. To remove a speaker, select it in the speaker&apos;s list and click on &quot;Remove&quot;. You are also able to adjust speaking time. 的本地化字符串。
        /// </summary>
        public static string h6p1eng {
            get {
                return ResourceManager.GetString("h6p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击正在进行的或左栏中的“主发言名单”以确立主发言名单。在左侧的列表中选择发言人并单击“添加”。然而，一个更有效率的方案是在搜索栏中输入国家名，并使用上下键选择，最终按下回车以添加。如需移除发言人，在主发言名单中选择，然后单击“移除”。您也可以调整发言时间。 的本地化字符串。
        /// </summary>
        public static string h6p1schn {
            get {
                return ResourceManager.GetString("h6p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set up a List 的本地化字符串。
        /// </summary>
        public static string h6p1teng {
            get {
                return ResourceManager.GetString("h6p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确立名单 的本地化字符串。
        /// </summary>
        public static string h6p1tschn {
            get {
                return ResourceManager.GetString("h6p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When you are satisfied with the list, click on &quot;Resume List&quot; to start or resume the speaker&apos;s list. use buttons on the top-left corner (Start, Pause, and Next) to time. Delegates spoken will be removed from the list, and you can keep inviting speakers as well.
        ///
        ///If you want to start a new event, such as raising a motion or voting, you must pause the timer first. When any other event is started, the speaker&apos;s list will be automatically paused, and you will need to click on &quot;Resume List&quot; again after the even [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string h6p2eng {
            get {
                return ResourceManager.GetString("h6p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当名单完成后，单击“继续名单”以开始或继续主发言名单。使用左上角的按钮（开始、暂停和下一位）以计时。发言完毕的代表会被移出名单，您也可以继续添加发言人。
        ///
        ///若您欲开始新事项，如动议或投票，您应当先暂停计时。当任何其他事项开始时，主发言名单会被自动暂停。您将会需要重新单击“继续名单”以回到主发言名单。 的本地化字符串。
        /// </summary>
        public static string h6p2schn {
            get {
                return ResourceManager.GetString("h6p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Time 的本地化字符串。
        /// </summary>
        public static string h6p2teng {
            get {
                return ResourceManager.GetString("h6p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时 的本地化字符串。
        /// </summary>
        public static string h6p2tschn {
            get {
                return ResourceManager.GetString("h6p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speaker&apos;s List 的本地化字符串。
        /// </summary>
        public static string h6teng {
            get {
                return ResourceManager.GetString("h6teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主发言名单 的本地化字符串。
        /// </summary>
        public static string h6tschn {
            get {
                return ResourceManager.GetString("h6tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When no other event is underway, click on &quot;Roll Call&quot; to go to the attendance status page. Click on &quot;Start Roll Call&quot; to conduct a roll call.
        ///
        ///Multi-task is supported in the progress, but no new event should start until roll call is completed or canceled. 的本地化字符串。
        /// </summary>
        public static string h7p1eng {
            get {
                return ResourceManager.GetString("h7p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当没有其他事项正在进行时，单击“点名程序”以访问出席情况页面。单击“开始点名”以进行点名。
        ///
        ///在这个过程中，您可以继续处理其他会议事务，但不能开始新事项，直到点名完成或取消。 的本地化字符串。
        /// </summary>
        public static string h7p1schn {
            get {
                return ResourceManager.GetString("h7p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Roll Call 的本地化字符串。
        /// </summary>
        public static string h7p1teng {
            get {
                return ResourceManager.GetString("h7p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始点名 的本地化字符串。
        /// </summary>
        public static string h7p1tschn {
            get {
                return ResourceManager.GetString("h7p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After roll call begins, choose the attendance status of each delegate. To modify the status of delegates called, select in the list and make changes. When all delegates have been called, roll call is completed. 的本地化字符串。
        /// </summary>
        public static string h7p2eng {
            get {
                return ResourceManager.GetString("h7p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点名程序开始后，依次选择各代表的出席情况。若需修改已点名的代表的出席情况，请直接在列表中选择修改。当所有代表都被点到后，点名程序即终止。 的本地化字符串。
        /// </summary>
        public static string h7p2schn {
            get {
                return ResourceManager.GetString("h7p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do Roll Call 的本地化字符串。
        /// </summary>
        public static string h7p2teng {
            get {
                return ResourceManager.GetString("h7p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进行点名 的本地化字符串。
        /// </summary>
        public static string h7p2tschn {
            get {
                return ResourceManager.GetString("h7p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The software uses the following formulas to calculate majorities, only for reference:
        ///
        ///Simple Majority: (Present + 1) / 2, rounded up to the nearest integer;
        ///
        ///Absolute Majority: Present * (2 / 3), rounded up to the nearest integer;
        ///
        ///20% of the Number: Present * 20%, rounded up to the nearest integer;
        ///
        ///Attendance Rate: Present / All, rounded down to the nearest integer. 的本地化字符串。
        /// </summary>
        public static string h7p3eng {
            get {
                return ResourceManager.GetString("h7p3eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件使用以下公式以计算多数，仅供参考：
        ///
        ///简单多数：（出席 + 1）/ 2，向上取整；
        ///
        ///绝对多数：出席 * （2 / 3），向上取整；
        ///
        ///百分之二十数：出席 * 20%，向上取整；
        ///
        ///出席率：出席 / 所有，向下取整。 的本地化字符串。
        /// </summary>
        public static string h7p3schn {
            get {
                return ResourceManager.GetString("h7p3schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Majorities 的本地化字符串。
        /// </summary>
        public static string h7p3teng {
            get {
                return ResourceManager.GetString("h7p3teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多数 的本地化字符串。
        /// </summary>
        public static string h7p3tschn {
            get {
                return ResourceManager.GetString("h7p3tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roll Call 的本地化字符串。
        /// </summary>
        public static string h7teng {
            get {
                return ResourceManager.GetString("h7teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点名 的本地化字符串。
        /// </summary>
        public static string h7tschn {
            get {
                return ResourceManager.GetString("h7tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When no other event is underway, click on &quot;Voting&quot; to go to the voting page. Enter the name of the paper to vote, and click on &quot;Start Voting&quot; to conduct a voting.
        ///
        ///Multi-task is supported in the progress, but no new event should start until voting is completed or canceled. 的本地化字符串。
        /// </summary>
        public static string h8p1eng {
            get {
                return ResourceManager.GetString("h8p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当没有其他事项正在进行时，单击“投票程序”以访问投票页面。输入要表决的文件名，然后单击“开始投票”以进行投票。
        ///
        ///在这个过程中，您可以继续处理其他会议事务，但不能开始新事项，直到投票完成或取消。 的本地化字符串。
        /// </summary>
        public static string h8p1schn {
            get {
                return ResourceManager.GetString("h8p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Voting 的本地化字符串。
        /// </summary>
        public static string h8p1teng {
            get {
                return ResourceManager.GetString("h8p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始投票 的本地化字符串。
        /// </summary>
        public static string h8p1tschn {
            get {
                return ResourceManager.GetString("h8p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the first round of voting, the options of Yes, No, Pass, and Abstain are provided. Choose the preference of each country. 的本地化字符串。
        /// </summary>
        public static string h8p2eng {
            get {
                return ResourceManager.GetString("h8p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在第一轮投票中，有赞成、反对、过或弃权可供选择。依次选择每个国家的意向。 的本地化字符串。
        /// </summary>
        public static string h8p2schn {
            get {
                return ResourceManager.GetString("h8p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Round 的本地化字符串。
        /// </summary>
        public static string h8p2teng {
            get {
                return ResourceManager.GetString("h8p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一轮 的本地化字符串。
        /// </summary>
        public static string h8p2tschn {
            get {
                return ResourceManager.GetString("h8p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Start 2nd Round&quot; to move on to the second round of voting. Only Yes and No are available, and only delegates voted Pass in the first round are allowed to vote in this round. 的本地化字符串。
        /// </summary>
        public static string h8p3eng {
            get {
                return ResourceManager.GetString("h8p3eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击“开始二轮投票”以继续进行第二轮投票。只有在第一轮中投“过”的代表能够在本轮投票，且只有“赞成”或“反对”可供选择。 的本地化字符串。
        /// </summary>
        public static string h8p3schn {
            get {
                return ResourceManager.GetString("h8p3schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second Round 的本地化字符串。
        /// </summary>
        public static string h8p3teng {
            get {
                return ResourceManager.GetString("h8p3teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第二轮 的本地化字符串。
        /// </summary>
        public static string h8p3tschn {
            get {
                return ResourceManager.GetString("h8p3tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Confirm Result&quot; to end the voting. Number of Yes, No and Abstain votes will be displayed, as well as Favor Rate, which is calculated by Yes / (Yes + No), rounded down to the nearest integer. Please announce the result according to rules and procedures. 的本地化字符串。
        /// </summary>
        public static string h8p4eng {
            get {
                return ResourceManager.GetString("h8p4eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击“确认投票结果”以结束投票。赞成、反对和弃权的人数以及赞成率（赞成 / （赞成 + 反对），向下取整）会被展示。请自行按照议事规则宣布文件是否通过。 的本地化字符串。
        /// </summary>
        public static string h8p4schn {
            get {
                return ResourceManager.GetString("h8p4schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string h8p4teng {
            get {
                return ResourceManager.GetString("h8p4teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        public static string h8p4tschn {
            get {
                return ResourceManager.GetString("h8p4tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voting Procedure 的本地化字符串。
        /// </summary>
        public static string h8teng {
            get {
                return ResourceManager.GetString("h8teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票程序 的本地化字符串。
        /// </summary>
        public static string h8tschn {
            get {
                return ResourceManager.GetString("h8tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on &quot;Data and File&quot; in the left column. You can save or output conference progress in the data section, including events, delegate data, and file records.
        ///
        ///Conference progress is saved in Country.txt, Event.txt, File.txt and Data.txt under the application startup path, and will be reloaded into the software next time when launching it. To avoid any malfunction, DO NOT modify these text files. To start a new record, simply remove these files (except Country.txt), or move the program to another path, a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string h9p1eng {
            get {
                return ResourceManager.GetString("h9p1eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单击左栏中的“文件与数据”。您可以在数据部分中保存或导出会议进程，包括动态、代表数据和文件记录。
        ///
        ///会议进度被保存在软件根目录下的 Country.txt、Event.txt、File.txt 和 Data.txt 中，并会在下次启动软件时被加载。为防止错误的发生，请勿修改任何任何一个文本文档。若需重新开始记录，只需移除这些文档（Country.txt 除外），或移动软件至新目录并重新启动。若您对 Country.txt 进行了更改，请删除 data.txt 和 file.txt 以避免任何Bug或数据错位。 的本地化字符串。
        /// </summary>
        public static string h9p1schn {
            get {
                return ResourceManager.GetString("h9p1schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Conference Progress 的本地化字符串。
        /// </summary>
        public static string h9p1teng {
            get {
                return ResourceManager.GetString("h9p1teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存会议进度 的本地化字符串。
        /// </summary>
        public static string h9p1tschn {
            get {
                return ResourceManager.GetString("h9p1tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conference progress can also be output in human-readable contents, but the output record cannot be reloaded. 的本地化字符串。
        /// </summary>
        public static string h9p2eng {
            get {
                return ResourceManager.GetString("h9p2eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会议进度也可被导出为人类可读的内容，但导出的记录不能被重新加载。 的本地化字符串。
        /// </summary>
        public static string h9p2schn {
            get {
                return ResourceManager.GetString("h9p2schn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Conference Progress 的本地化字符串。
        /// </summary>
        public static string h9p2teng {
            get {
                return ResourceManager.GetString("h9p2teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出会议进度 的本地化字符串。
        /// </summary>
        public static string h9p2tschn {
            get {
                return ResourceManager.GetString("h9p2tschn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save and Output 的本地化字符串。
        /// </summary>
        public static string h9teng {
            get {
                return ResourceManager.GetString("h9teng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存与导出 的本地化字符串。
        /// </summary>
        public static string h9tschn {
            get {
                return ResourceManager.GetString("h9tschn", resourceCulture);
            }
        }
    }
}
